export const SET_AUTHENTICATED_USER = "SET_AUTHENTICATED_USER";
export const GET_ERRORS = "GET_ERRORS";
export const GET_USERS = "GET_USERS";
export const SET_AUTHENTICATING = "SET_AUTHENTICATING";
export const REGISTER_USERS = "REGISTER_USERS";
export const REGISTERING_USERS = "REGISTERING_USERS";
